name: Build Windows Executable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build Release Binary
        run: cargo build --locked --release --features channel-prod --bin sc

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: sc-windows-exe
          path: target/release/sc.exe
